"""add llm_usage_logs table

Revision ID: 293e3c5073ee
Revises:
Create Date: 2026-09-28 18:56:51.220412

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "293e3c5073ee"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "llm_usage_logs",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.Column("updated_at", sa.DATETIME(), nullable=True),
        sa.Column("service_name", sa.VARCHAR(), nullable=False),
        sa.Column("model", sa.VARCHAR(), nullable=False),
        sa.Column("caller_service_name", sa.VARCHAR(), nullable=False),
        sa.Column("user_id", sa.VARCHAR(length=100), nullable=True),
        sa.Column("tenant_id", sa.VARCHAR(length=100), nullable=True),
        sa.Column("session_id", sa.VARCHAR(length=100), nullable=True),
        sa.Column("prompt_tokens", sa.INTEGER(), nullable=True),
        sa.Column("completion_tokens", sa.INTEGER(), nullable=True),
        sa.Column("total_tokens", sa.INTEGER(), nullable=True),
        sa.Column("cache_read_tokens", sa.INTEGER(), nullable=True),
        sa.Column("cache_creation_tokens", sa.INTEGER(), nullable=True),
        sa.Column("cost", sa.NUMERIC(precision=12, scale=6), nullable=True),
        sa.Column("latency_ms", sa.INTEGER(), nullable=True),
        sa.Column("status_code", sa.INTEGER(), nullable=True),
        sa.Column("is_success", sa.BOOLEAN(), nullable=True),
        sa.Column("error_message", sa.TEXT(), nullable=True),
        sa.Column("finish_reason", sa.VARCHAR(length=50), nullable=True),
        sa.Column("temperature", sa.NUMERIC(precision=3, scale=2), nullable=True),
        sa.Column("max_tokens", sa.INTEGER(), nullable=True),
        sa.Column("input_text", sa.TEXT(), nullable=True),
        sa.Column("output_text", sa.TEXT(), nullable=True),
        sa.Column("extra_metadata", sqlite.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_llm_usage_logs_user_id"), "llm_usage_logs", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_llm_usage_logs_tenant_id"),
        "llm_usage_logs",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_llm_usage_logs_session_id"),
        "llm_usage_logs",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_llm_usage_logs_service_name"),
        "llm_usage_logs",
        ["service_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_llm_usage_logs_model"), "llm_usage_logs", ["model"], unique=False
    )
    op.create_index(
        op.f("ix_llm_usage_logs_is_success"),
        "llm_usage_logs",
        ["is_success"],
        unique=False,
    )
    op.create_index(
        op.f("ix_llm_usage_logs_id"), "llm_usage_logs", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_llm_usage_logs_created_at"),
        "llm_usage_logs",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_llm_usage_logs_caller_service_name"),
        "llm_usage_logs",
        ["caller_service_name"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_llm_usage_logs_caller_service_name"), table_name="llm_usage_logs"
    )
    op.drop_index(op.f("ix_llm_usage_logs_created_at"), table_name="llm_usage_logs")
    op.drop_index(op.f("ix_llm_usage_logs_id"), table_name="llm_usage_logs")
    op.drop_index(op.f("ix_llm_usage_logs_is_success"), table_name="llm_usage_logs")
    op.drop_index(op.f("ix_llm_usage_logs_model"), table_name="llm_usage_logs")
    op.drop_index(op.f("ix_llm_usage_logs_service_name"), table_name="llm_usage_logs")
    op.drop_index(op.f("ix_llm_usage_logs_session_id"), table_name="llm_usage_logs")
    op.drop_index(op.f("ix_llm_usage_logs_tenant_id"), table_name="llm_usage_logs")
    op.drop_index(op.f("ix_llm_usage_logs_user_id"), table_name="llm_usage_logs")
    op.drop_table("llm_usage_logs")
    # ### end Alembic commands ###
