"""add extended intent fields to gateway request log

Revision ID: 328f1aec9825
Revises: e87d6735d896
Create Date: 2026-10-03 15:48:59.224372

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "328f1aec9825"
down_revision: str | Sequence[str] | None = "e87d6735d896"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gateway_requests",
        sa.Column("core_operation", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "gateway_requests",
        sa.Column("subject_modifier", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "gateway_requests",
        sa.Column("action_modifier", sa.String(length=255), nullable=True),
    )
    op.create_index(
        op.f("ix_gateway_requests_action_modifier"),
        "gateway_requests",
        ["action_modifier"],
        unique=False,
    )
    op.create_index(
        op.f("ix_gateway_requests_core_operation"),
        "gateway_requests",
        ["core_operation"],
        unique=False,
    )
    op.create_index(
        op.f("ix_gateway_requests_subject_modifier"),
        "gateway_requests",
        ["subject_modifier"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_gateway_requests_subject_modifier"), table_name="gateway_requests"
    )
    op.drop_index(
        op.f("ix_gateway_requests_core_operation"), table_name="gateway_requests"
    )
    op.drop_index(
        op.f("ix_gateway_requests_action_modifier"), table_name="gateway_requests"
    )
    op.drop_column("gateway_requests", "action_modifier")
    op.drop_column("gateway_requests", "subject_modifier")
    op.drop_column("gateway_requests", "core_operation")
    # ### end Alembic commands ###
