"""add llm_quota_rules table

Revision ID: 5281767163ee
Revises: 293e3c5073ee
Create Date: 2026-09-29 01:16:03.138406

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5281767163ee"
down_revision: str | Sequence[str] | None = "293e3c5073ee"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "llm_quota_rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("provider", sa.String(length=50), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("user_id", sa.String(length=100), nullable=True),
        sa.Column("tenant_id", sa.String(length=100), nullable=True),
        sa.Column("max_rpm", sa.Integer(), nullable=True),
        sa.Column("max_tpm", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_llm_quota_rules_created_at"),
        "llm_quota_rules",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_llm_quota_rules_id"), "llm_quota_rules", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_llm_quota_rules_model"), "llm_quota_rules", ["model"], unique=False
    )
    op.create_index(
        op.f("ix_llm_quota_rules_provider"),
        "llm_quota_rules",
        ["provider"],
        unique=False,
    )
    op.create_index(
        op.f("ix_llm_quota_rules_tenant_id"),
        "llm_quota_rules",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_llm_quota_rules_user_id"), "llm_quota_rules", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_llm_quota_rules_user_id"), table_name="llm_quota_rules")
    op.drop_index(op.f("ix_llm_quota_rules_tenant_id"), table_name="llm_quota_rules")
    op.drop_index(op.f("ix_llm_quota_rules_provider"), table_name="llm_quota_rules")
    op.drop_index(op.f("ix_llm_quota_rules_model"), table_name="llm_quota_rules")
    op.drop_index(op.f("ix_llm_quota_rules_id"), table_name="llm_quota_rules")
    op.drop_index(op.f("ix_llm_quota_rules_created_at"), table_name="llm_quota_rules")
    op.drop_table("llm_quota_rules")
    # ### end Alembic commands ###
