"""remove cross_encoder_score

Revision ID: 79ffbec3616a
Revises: cb2a4117a54c
Create Date: 2026-10-04 21:49:43.489620

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "79ffbec3616a"
down_revision: str | Sequence[str] | None = "cb2a4117a54c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("gateway_requests", "cross_encoder_score")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gateway_requests",
        sa.Column(
            "cross_encoder_score", sa.NUMERIC(precision=5, scale=4), nullable=True
        ),
    )
    # ### end Alembic commands ###
