"""Add cost_calculated flag

Revision ID: b09cd2a3f8c8
Revises: 5281767163ee
Create Date: 2026-09-29 17:42:19.133014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b09cd2a3f8c8'
down_revision: Union[str, Sequence[str], None] = '5281767163ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_usage_logs', sa.Column('cost_calculated', sa.Boolean(), server_default='0', nullable=True))
    op.create_index(op.f('ix_llm_usage_logs_cost_calculated'), 'llm_usage_logs', ['cost_calculated'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_usage_logs_cost_calculated'), table_name='llm_usage_logs')
    op.drop_column('llm_usage_logs', 'cost_calculated')
    # ### end Alembic commands ###
