"""add_latency_breakdown_to_gateway_requests

Revision ID: bb35f2041f68
Revises: 79ffbec3616a
Create Date: 2026-10-06 14:12:16.249652

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bb35f2041f68"
down_revision: str | Sequence[str] | None = "79ffbec3616a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gateway_requests",
        sa.Column("provider_latency_ms", sa.Integer(), nullable=True),
    )
    op.add_column(
        "gateway_requests",
        sa.Column("cache_lookup_latency_ms", sa.Integer(), nullable=True),
    )
    op.add_column(
        "gateway_requests", sa.Column("latency_breakdown", sa.JSON(), nullable=True)
    )
    op.create_index(
        op.f("ix_gateway_requests_provider_latency_ms"),
        "gateway_requests",
        ["provider_latency_ms"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_gateway_requests_provider_latency_ms"), table_name="gateway_requests"
    )
    op.drop_column("gateway_requests", "latency_breakdown")
    op.drop_column("gateway_requests", "cache_lookup_latency_ms")
    op.drop_column("gateway_requests", "provider_latency_ms")
    # ### end Alembic commands ###
