"""add conversation_id to llm_usage_log table

Revision ID: cb2a4117a54c
Revises: 328f1aec9825
Create Date: 2026-10-03 17:22:34.613067

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cb2a4117a54c"
down_revision: str | Sequence[str] | None = "328f1aec9825"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gateway_requests",
        sa.Column("session_id", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "gateway_requests",
        sa.Column("conversation_id", sa.String(length=100), nullable=True),
    )
    op.create_index(
        op.f("ix_gateway_requests_conversation_id"),
        "gateway_requests",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_gateway_requests_session_id"),
        "gateway_requests",
        ["session_id"],
        unique=False,
    )
    op.add_column(
        "llm_usage_logs",
        sa.Column("conversation_id", sa.String(length=100), nullable=True),
    )
    op.create_index(
        op.f("ix_llm_usage_logs_conversation_id"),
        "llm_usage_logs",
        ["conversation_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_llm_usage_logs_conversation_id"), table_name="llm_usage_logs"
    )
    op.drop_column("llm_usage_logs", "conversation_id")
    op.drop_index(op.f("ix_gateway_requests_session_id"), table_name="gateway_requests")
    op.drop_index(
        op.f("ix_gateway_requests_conversation_id"), table_name="gateway_requests"
    )
    op.drop_column("gateway_requests", "conversation_id")
    op.drop_column("gateway_requests", "session_id")
    # ### end Alembic commands ###
