"""Add gateway requests log table

Revision ID: e87d6735d896
Revises: b09cd2a3f8c8
Create Date: 2026-10-03 01:26:13.641650

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e87d6735d896"
down_revision: str | Sequence[str] | None = "b09cd2a3f8c8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gateway_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("query_text", sa.Text(), nullable=False),
        sa.Column("response_text", sa.Text(), nullable=True),
        sa.Column("routing_decision", sa.String(length=50), nullable=False),
        sa.Column("provider", sa.String(length=100), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("point_id", sa.String(length=36), nullable=True),
        sa.Column("exact_hash", sa.String(length=64), nullable=True),
        sa.Column("intent", sa.String(length=100), nullable=True),
        sa.Column("core_subject", sa.String(length=255), nullable=True),
        sa.Column("rerank_score", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.String(length=100), nullable=True),
        sa.Column("tenant_id", sa.String(length=100), nullable=True),
        sa.Column("evaluation_status", sa.String(length=20), nullable=True),
        sa.Column(
            "cross_encoder_score", sa.Numeric(precision=5, scale=4), nullable=True
        ),
        sa.Column(
            "llm_relevance_score", sa.Numeric(precision=5, scale=4), nullable=True
        ),
        sa.Column(
            "llm_contradiction_score", sa.Numeric(precision=5, scale=4), nullable=True
        ),
        sa.Column(
            "llm_instruction_score", sa.Numeric(precision=5, scale=4), nullable=True
        ),
        sa.Column("is_false_positive", sa.Boolean(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_gateway_requests_core_subject"),
        "gateway_requests",
        ["core_subject"],
        unique=False,
    )
    op.create_index(
        op.f("ix_gateway_requests_created_at"),
        "gateway_requests",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_gateway_requests_evaluation_status"),
        "gateway_requests",
        ["evaluation_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_gateway_requests_exact_hash"),
        "gateway_requests",
        ["exact_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_gateway_requests_id"), "gateway_requests", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_gateway_requests_intent"), "gateway_requests", ["intent"], unique=False
    )
    op.create_index(
        op.f("ix_gateway_requests_is_false_positive"),
        "gateway_requests",
        ["is_false_positive"],
        unique=False,
    )
    op.create_index(
        op.f("ix_gateway_requests_point_id"),
        "gateway_requests",
        ["point_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_gateway_requests_routing_decision"),
        "gateway_requests",
        ["routing_decision"],
        unique=False,
    )
    op.create_index(
        op.f("ix_gateway_requests_tenant_id"),
        "gateway_requests",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_gateway_requests_user_id"),
        "gateway_requests",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_gateway_requests_user_id"), table_name="gateway_requests")
    op.drop_index(op.f("ix_gateway_requests_tenant_id"), table_name="gateway_requests")
    op.drop_index(
        op.f("ix_gateway_requests_routing_decision"), table_name="gateway_requests"
    )
    op.drop_index(op.f("ix_gateway_requests_point_id"), table_name="gateway_requests")
    op.drop_index(
        op.f("ix_gateway_requests_is_false_positive"), table_name="gateway_requests"
    )
    op.drop_index(op.f("ix_gateway_requests_intent"), table_name="gateway_requests")
    op.drop_index(op.f("ix_gateway_requests_id"), table_name="gateway_requests")
    op.drop_index(op.f("ix_gateway_requests_exact_hash"), table_name="gateway_requests")
    op.drop_index(
        op.f("ix_gateway_requests_evaluation_status"), table_name="gateway_requests"
    )
    op.drop_index(op.f("ix_gateway_requests_created_at"), table_name="gateway_requests")
    op.drop_index(
        op.f("ix_gateway_requests_core_subject"), table_name="gateway_requests"
    )
    op.drop_table("gateway_requests")
    # ### end Alembic commands ###
