import os

# Provider & Fallback Defaults
DEFAULT_LLM_SERVICE = os.getenv("DEFAULT_LLM_SERVICE", "ollama")
FALLBACK_LLM_SERVICE = os.getenv("FALLBACK_LLM_SERVICE", "ollama")
FALLBACK_LLM_MODEL = os.getenv("FALLBACK_LLM_MODEL", "llama3.1:8b")

# Timeouts & Retries
LLM_PROVIDER_TIMEOUT_SECONDS = float(os.getenv("LLM_PROVIDER_TIMEOUT_SECONDS", "15.0"))
LLM_MAX_RETRIES = int(os.getenv("LLM_MAX_RETRIES", "0"))
RETRY_BACKOFF_INITIAL_SECONDS = int(os.getenv("RETRY_BACKOFF_INITIAL_SECONDS", "1"))
RETRY_BACKOFF_MAX_SECONDS = int(os.getenv("RETRY_BACKOFF_MAX_SECONDS", "10"))

# Semantic Search & Cache Tuning
QDRANT_SEARCH_THRESHOLD = float(os.getenv("QDRANT_SEARCH_THRESHOLD", "0.70"))
QDRANT_SEARCH_LIMIT = int(os.getenv("QDRANT_SEARCH_LIMIT", "10"))
DEFAULT_CACHE_TTL_SECONDS = int(
    os.getenv("DEFAULT_CACHE_TTL_SECONDS", str(1 * 24 * 60 * 60))
)

# Model Configuration
EMBEDDING_MODEL_NAME = os.getenv("EMBEDDING_MODEL_NAME", "all-MiniLM-L6-v2")
RERANKER_MODEL_NAME = os.getenv("RERANKER_MODEL_NAME", "BAAI/bge-reranker-base")
INTENT_CLASSIFIER_MODEL = os.getenv("INTENT_CLASSIFIER_MODEL", "qwen2.5-coder:1.5b")
INTENT_CLASSIFIER_SERVICE = os.getenv("INTENT_CLASSIFIER_SERVICE", "ollama")
